// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `person.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct person {
    // message fields
    pub lastname: ::std::string::String,
    pub firstname: ::std::string::String,
    pub dateofbirth: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a person {
    fn default() -> &'a person {
        <person as ::protobuf::Message>::default_instance()
    }
}

impl person {
    pub fn new() -> person {
        ::std::default::Default::default()
    }

    // string lastname = 1;


    pub fn get_lastname(&self) -> &str {
        &self.lastname
    }
    pub fn clear_lastname(&mut self) {
        self.lastname.clear();
    }

    // Param is passed by value, moved
    pub fn set_lastname(&mut self, v: ::std::string::String) {
        self.lastname = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_lastname(&mut self) -> &mut ::std::string::String {
        &mut self.lastname
    }

    // Take field
    pub fn take_lastname(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.lastname, ::std::string::String::new())
    }

    // string firstname = 2;


    pub fn get_firstname(&self) -> &str {
        &self.firstname
    }
    pub fn clear_firstname(&mut self) {
        self.firstname.clear();
    }

    // Param is passed by value, moved
    pub fn set_firstname(&mut self, v: ::std::string::String) {
        self.firstname = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_firstname(&mut self) -> &mut ::std::string::String {
        &mut self.firstname
    }

    // Take field
    pub fn take_firstname(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.firstname, ::std::string::String::new())
    }

    // string dateofbirth = 3;


    pub fn get_dateofbirth(&self) -> &str {
        &self.dateofbirth
    }
    pub fn clear_dateofbirth(&mut self) {
        self.dateofbirth.clear();
    }

    // Param is passed by value, moved
    pub fn set_dateofbirth(&mut self, v: ::std::string::String) {
        self.dateofbirth = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dateofbirth(&mut self) -> &mut ::std::string::String {
        &mut self.dateofbirth
    }

    // Take field
    pub fn take_dateofbirth(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.dateofbirth, ::std::string::String::new())
    }
}

impl ::protobuf::Message for person {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.lastname)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.firstname)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.dateofbirth)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.lastname.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.lastname);
        }
        if !self.firstname.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.firstname);
        }
        if !self.dateofbirth.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.dateofbirth);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.lastname.is_empty() {
            os.write_string(1, &self.lastname)?;
        }
        if !self.firstname.is_empty() {
            os.write_string(2, &self.firstname)?;
        }
        if !self.dateofbirth.is_empty() {
            os.write_string(3, &self.dateofbirth)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> person {
        person::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "lastname",
                |m: &person| { &m.lastname },
                |m: &mut person| { &mut m.lastname },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "firstname",
                |m: &person| { &m.firstname },
                |m: &mut person| { &mut m.firstname },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "dateofbirth",
                |m: &person| { &m.dateofbirth },
                |m: &mut person| { &mut m.dateofbirth },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<person>(
                "person",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static person {
        static instance: ::protobuf::rt::LazyV2<person> = ::protobuf::rt::LazyV2::INIT;
        instance.get(person::new)
    }
}

impl ::protobuf::Clear for person {
    fn clear(&mut self) {
        self.lastname.clear();
        self.firstname.clear();
        self.dateofbirth.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for person {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for person {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cperson.proto\"d\n\x06person\x12\x1a\n\x08lastname\x18\x01\x20\x01(\
    \tR\x08lastname\x12\x1c\n\tfirstname\x18\x02\x20\x01(\tR\tfirstname\x12\
    \x20\n\x0bdateofbirth\x18\x03\x20\x01(\tR\x0bdateofbirthb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
